name: 'Force bump veersion to "version: patch"'
description: ''
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Force to "version: patch" label'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        labels: 'version: patch'
